# Gunakan image Node.js resmi sebagai image dasar
FROM node:latest

# Tentukan direktori kerja dalam container
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json ke direktori kerja
COPY package*.json ./

# Instal dependensi aplikasi
RUN npm install

# Salin sisa kode aplikasi ke dalam direktori kerja
COPY . .

# Expose port yang digunakan oleh aplikasi
EXPOSE 3000

# Tentukan perintah untuk menjalankan aplikasi
CMD ["npm", "start"]
